### ISSUE TITLE
Change the time format

### ISSUE THREAD

**Issue by adambatchi** [tuannvm2109/time_picker_spinner_pop_up#12]
HI,
I made some changes on the package so it can be 24 format or 12 format in Time mode
here is the changes and the files

time_picker_spinner_pop_up.dart : 385
`use24hFormat: widget.format24 ?? false,`

time_picker_spinner_pop_up.dart : under line 11 add
`this.format24,`

so at the end it will be like this

`TimePickerSpinnerPopUp(
      format24: false,.......`

**Comment by tuannvm2109** [comment]
Thank you, I will add this on next version

**Comment by tuannvm2109** [comment]
I have added it to version 1.4.0, you can check it again on pub.dev
