### ISSUE TITLE
Dose this lib support changing locale?

### ISSUE THREAD

**Issue by March-mitsuki** [tuannvm2109/time_picker_spinner_pop_up#14]
Hello, thank you for maintaining this package. 

Does this lib support changing locale? I seem not to have found a api where I can change it.

**Comment by tuannvm2109** [comment]
This lib use locale from MaterialApp, you can change the locale from there

```
MaterialApp(
      ...
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        DefaultCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('en', 'US'), // English
      ],
      home: const MyHomePage(title: 'Time Picker Spinner Pop Up'),
    )
```

**Comment by March-mitsuki** [comment]
Thank you for your quick reply. Doing so indeed changed the Locale. Thank you very much!

**Comment by tuannvm2109** [comment]
If you want to set a custom locale, please try version 1.5.0, which was recently public on pub.dev
