### ISSUE TITLE
Timepicker in 5 min (Custom set) step increments

### ISSUE THREAD

**Issue by Vanhayten** [tuannvm2109/time_picker_spinner_pop_up#5]
https://github.com/tuannvm2109/time_picker_spinner_pop_up/blob/bd34897f5fae28a220f10b72603eb30dcd8d3921/lib/time_picker_spinner_pop_up.dart#L251

I add this ` minuteInterval: 5,`  manually its good if it is a params like 
` minimumDate: widget.minTime,
   maximumDate: widget.maxTime,`

**Comment by tuannvm2109** [comment]
Thank you for your feedback, I have added this to version 1.1.0
