### ISSUE TITLE
this date picker not working

### ISSUE THREAD

**Issue by abdessamadpas** [tuannvm2109/time_picker_spinner_pop_up#8]
this date picker not working when i select a value its return to the initial value after the spring 
and i check the to run the example in ur repo the same problem

**Comment by tuannvm2109** [comment]
This date picker will alway use initTime to show, after you pick a `dateTime`, you should setState to change your time

```
initTime: time,
onChange: (dateTime) {
        setState(() {
         time = dateTime;
        });
 },
```

**Comment by abdessamadpas** [comment]
there is a bug there , i switch it to work with Getx,  u made a cool thing dude,
